- packages/sdk/layer1/index.js
- packages/sdk/layer2/index.js
- packages/sdk/theme-dropin/package.json
- packages/sdk/theme-dropin/src/index.js
- packages/sdk/theme-dropin/yarn.lock
no-issue (@rishabhgrg do we need to make one? or just a note? if it's a note I'm not sure what we doing about ref-ing those in commits etc...)
We had some bugs in the paid site flow, where when a user was to upgrade from free to paid, they would be shown an upgrade button still. This was due to caching of tokens. There was a similar issue that happened when signing up as a paid user.
The fix here ensures that we request a "fresh" token, which will contain the current state of the user and their plans.
> Fixed issue with stale tokens on signup/upgrade to paid site.

- packages/members-auth-pages/components/MembersProvider.js
- packages/members-auth-pages/index.js
refs https://github.com/TryGhost/Ghost/issues/10886
Since updating the static pages, the auth pages would be broken, this
updates them to correctly parse and load the static urls.
> Updated auth-pages to use new members static url

- packages/members-auth-pages/components/Pages.js
- packages/members-browser-auth/index.js
This updates the auth-pages to change the location hash from within the iframe, and the browser auth to post a message asking it to do so.
> Fix auth pages flashing

- packages/members-ssr/index.js
no-issue
This is to allow support for consumers to dynamically update their
membersApi instance, for example when configuration changes, and not
have to replace the instance of members-ssr
> Added support for passing thunk for membersApi

- packages/members-api/index.js
- packages/members-ssr/index.js
This adds another cookie to the `members-ssr` module to old cached members data - meaning that expensive calls from the `members-api` module are not executed on every request. An extra cookie has been used because it was a) fast and b) still secured with crypto signature.
> Added caching to members-ssr module

- packages/members-ssr/example.js
- packages/members-ssr/index.js
- packages/members-ssr/package.json
- packages/members-ssr/tsconfig.json
- yarn.lock
no-issue
This changes the exchangeTokenForSession method to read the token from a
`token` query string, rather than from the request body.
This also includes a refactor to change MembersSSR into a class, and
document all methods with JsDoc type annotations which can be
interpreted by the typescript compiler
> Updated members-ssr to use token from query string

- packages/magic-link/index.js
- packages/magic-link/test/index.test.js
- packages/members-api/index.js
no-issue
This allows for multiple magic-link email templates by passing in a `type` parameter
> Support for multiple magic-link email templates

- packages/members-api/lib/users.js
no-issue
This allows create to have an optional second parameter, so that it
doesn't error when called with just data.
> Added default options param for users#create

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
no-issue
This will allow clients to customise where they are redirecting to after
the stripe checkout session is exited.
> Added support for custome success/cancel urls

- packages/members-api/lib/stripe/index.js
no issue 
- When debugging Stripe with using: `stripe listen \
--forward-to http://ghost.local/members/webhooks/stripe/` 
- This priority (fallback) is nice to have so that Ghost process can be initialized using WEBHOOK_SECRET env variable
@allouis had bumped into this issue a couple of times already. Think it makes sense or I'm missing something when using local instance?
> Added priority to webhook secret if present in env

- packages/members-api/index.js
- packages/members-api/lib/users.js
Refactor that allows member-api to use Ghost member models directly, also reduces member-api constructor signature.
Note: would require a minor bump because of the constructor signature change
@allouis would be great if you could verify if I understood the needed refactor correctly and this is the right direction :arrow_forward:
> Changed members-api constructor to accept Member model directly

- packages/members-api/index.js
- packages/members-api/lib/common.js
- packages/members-api/lib/stripe/index.js
Adds the ability to cancel member's subscriptions.
@allouis a structural question about this change. 
(i) Have placed validation handling (if the subscription exists and belongs to the member) in the route handler itself. Was wondering if this kind of checks might belong on the stripe class itself? 
(ii) Another topic is how the deletion is handled on our side. Right now the flow would be following:
1. Member visits the "account" page
2. Clicks on "cancel subscription" button
3. The request to cancel the subscription goes out to Stripe.
3.1. At some point, webhook about the cancellation comes back and we remove the record in the DB.
4. Frontend receives confirmation and member refreshes the page and still sees the subscription.
5. Refreshes again and it's gone (webhook came through) …
> Added subscription update middleware

- packages/members-api/lib/users.js
refs https://github.com/TryGhost/Members/commit/aa7c76a1d06aaae7ef9958cd5a60becc5db2ad62
While refactoring user CRUD for Ghost core, we inadvertently changed the members subscriptions object returned by nesting the value as object. This also broke the deserialization in Ghost-Admin for members subscription object [here](https://github.com/TryGhost/Ghost-Admin/blob/master/app/transforms/member-subscription.js#L9).
> 🐛 Fixed incorrect fetch of empty stripe subscriptions

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
Handling of of "Complimentary" (comp) subscription for members.
TODO:
> ✨ Added "complimentary" subscription handling

- packages/magic-link/index.js
- packages/members-api/index.js
- packages/members-api/lib/users.js
no issue
refs https://github.com/TryGhost/Ghost/pull/11538/files
We are adding new ability for site-owners to tag members using labels and perform actions like filtering using labels on Admin. We want site owners/theme builders to be able to tag members through the signup process, and corresponding label(s) should be saved to them respectively.
This PR adds ability in members-api package to use `data-members-label` property from theme for assigning labels to members during signup flow.
- Updates `sendMagicLink` middleware to read `labels` from request body
- Allows magic link email method to use labels
- Updates magic link token generation to encode labels if exist
- Read labels from magic link token data for member creation
- Updates member creation to pass labels
> ✨ Added ability to add labels to member signup

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
no issue
- Current update stripe subscription API calls only allowed cancelling a plan
- Adds option to pass plan's nickname as `planName` in request to update subscription to new plan
- - Checks if plan name passed is valid and updates stripe subscription to new plan at default prorate behavior
> Added plan update option to stripe subscription update API

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
refs https://github.com/TryGhost/members.js/issues/29
- Allows passing metadata with custom info like member name to stripe's checkout session which can be used from webhook event on checkout completion
- Uses the metadata option in stripe checkout flow to add member's name on creation via anonymous checkout flow
- Allows clients like memebrs.js to pass member's info like name from checkout signup flow
> Added metadata to stripe checkout session for member name

- packages/members-api/index.js
- packages/members-api/lib/metadata.js
- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
- packages/members-api/package.json
- yarn.lock
no-issue
This refactors the webhook creation to reuse an exisiting webhook when possible. This will stop an entire class of errors & bugs which were due to the webhook secret being stored in memory & the webhook endpoints being deleted.
> Refactor webhook creation

- packages/members-api/lib/stripe/index.js
no-issue
Due to a bug in Ghost webhooks are now created with a trailing "/" which
meant that the previous webhooks to that (without a slash) was never
removed.
This results in users receiving emails from stripe about failed webhook
delivery, which is not good at all.
This fix lists out the webhooks and finds (if present) the webhook which
matches the current URL, minus the trailing slash. If found it will then
attempt to delete that webhook thus stopping the emails from Stripe.
I've added a note to remove this code as it should only ever need to run
once, and can be removed for the Ghost release after these changes.
> Added cleanup on startup for old webhooks

- packages/members-api/index.js
no-issue
This fixes a problem when subscribing to a Plan (Price) with a default
trial period. We also add logging to add a little more information about
which flow we're entering.
Subscriptions that are started with a trial have a `setup_intent`
present on the Checkout Session object, which was incorrectly causing us
to determine that we are in a "setup" flow and attempt to update a
customers card details.
We now use the `mode` property of the Checkout Session to determine
whether we are handling a new Subscription, or if we are in a "setup"
flow and should update the Customer's card details.
> Used mode to determine flow for checkout session

- packages/members-api/lib/stripe/api/createDeterministicApi.js
refs https://github.com/TryGhost/Ghost/issues/12065
This protects us against multiple instances of the members-api being
started simultaneously and race conditions where inbetween the initial
"GET" of a plan which returns empty, and the "POST" of a plan to create
it, another instance has already created it.
> Caught & handled 'resource_already_exists' errors

- packages/members-api/lib/stripe/index.js
refs https://github.com/TryGhost/Ghost/issues/12074
refs https://github.com/TryGhost/Members/pull/18
Some sites may have had duplicate webhooks created due to a race
condition. This updates the members-api to cleanup _all_ webhooks before
starting, allowing it to create webhooks on a fresh slate, and removing
possible causes of 401 errors due to incorrect webhook secrets.
> Updated webhooks cleanup to handle all older webhooks

- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
no-issue
This updates the exposed method used to cancel stripe subscriptions name to `cancelStripeSubscriptions`, from `destroyStripeSubscriptions` to avoid confusion with the database/model layer.
We also add handling to errors when deleting/cancelling Stripe subscriptions so that any issues (such as the subscription already being cancelled) are logged, but do not disrupt the flow
> Updates for handling deletion of Members in Ghost

- packages/members-api/index.js
- packages/members-api/lib/metadata.js
no-issue
Previously we would blindly put subscriptions into the database when we
received a webhook, which could result in orphaned rows that were not
linked to a customer (and by extension a member)
This updates the logic so that we will only add subscriptions if we have
a record of their customer.
Customers are only added during a checkout.session.completed webhook, at
which point a member is guarunteed, but for formailty and safety against
changes in the flow, the logic has been applied to inserting customers
too.
> Ensured that we do not insert orphaned rows

- packages/members-api/lib/stripe/api/createStripeRequest.js
- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
- packages/members-api/package.json
- yarn.lock
no-issue
This updates the stripe module to handle rate limiting for us, so that Ghost Core/importer doesn't need to worry about it.
It also exposes some required stripe method like `getCustomer` `createCustomer` and `createComplimentarySubscription` - all of these methods only deal with the stripe side of things and will allow the consumer to handle updating the database
> Updates for bulk importer

- packages/magic-link/README.md
- packages/magic-link/index.js
- packages/magic-link/test/index.test.js
- packages/members-api/index.js
no-issue
This removes the concept of `subject` & `payload` from the function
signatures, making the implementation a little more generic, and less
JWT centric.
We also replace `getUserFromToken` and `getPayloadFromToken` with a single
method `getDataFromToken`, which will contain all the necessary data.
We also update `members-api` to work with the updates.
> Updated magic-link to be more generic

- packages/magic-link/JWTTokenProvider.js
- packages/magic-link/README.md
- packages/magic-link/index.js
- packages/magic-link/test/index.test.js
- packages/members-api/index.js
This adds a layer of abstraction between the magic-link module and the
token generation, allowing us to switch out the token generation in the
future, when implementing single use tokens stored in a database
> Updated MagicLink to accept a "TokenProvider"

- packages/members-api/index.js
no-issue
This paves the way for Ghost to be able to pass in a custom token
provider which will handle the shortening of tokens and making them
single use.
> Updated members-api to accept a TokenProvider

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
This PR adds support for Stripe's newly-added [promo code feature in Stripe Checkout](https://twitter.com/stripe/status/1291441519585406976). I've defaulted this value to `true` because it's fairly unobtrusive in the UI, and can safely be ignored if a new member subscribes and doesn't have a coupon to use.
The Stripe documentation on adding customer-facing promotion codes:
https://stripe.com/docs/payments/checkout/set-up-a-subscription#coupons
I've tested this with a local installation and found that it adds the promo code UI as expected (see included screenshots with PR). I then completed the checkout process with a coupon and found that it successfully applied the coupon - woohoo!
<details>
<summary>📷 Screenshots of the new coupon UI when redirected to Stripe Checkout</summary> …
> Add support for promo/coupon codes in Stripe Checkout

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
refs https://github.com/TryGhost/Ghost/issues/12055
This adds handling to the `update` method for members, which will check if the `email` property has changed on the member, and if so, iterate through all associated Stripe Customers, updating their email.
> Updated customer email in Stripe when member email changes

- packages/members-api/lib/stripe/index.js
no-issue
This is no longer necessary anymore, it would delete all webhooks which
matched the current webhook handler URL, which is undesirable
> Removed old webhook cleanup code

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
no-issue
Subscription created events are required for migrating Stripe subscriptions from
alternative platforms, which involves creating a new subscription for a customer
(outside of Ghost) before cancelling the original subscription.
> Added Stripe webhook listener for subscription created event

- packages/members-api/index.js
refs https://github.com/TryGhost/Ghost/issues/12270
Previously we would create the member, and then update their name from
stripe data, this mean that webhooks would be sent _without_ a name,
despite us possibly having the information to provide one.
Here we've updated the creation of members to include the name attached
to the default billing method, this will ensure that webhooks are sent
with all availiable information.
> Created member with name on checkout completion

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
refs https://github.com/TryGhost/Ghost/issues/12256 , https://github.com/TryGhost/Ghost/issues/12255
Currently when listing subscriptions for Members, we were only showing the subscriptions which have a status of trialing or active.
Based on discussion, the `unpaid` and `past_due` states on Stripe also represent owner's intention of considering a subscription as active instead of `cancelled`, so we allow any subscriptions under these 2 states to be also listed for a member and consider them as `paid`.
- Subscriptions will go into a past_due state if the payment is missed, this should be considered a grace period where the member still has access.
- After this the subscriptions will either go to the unpaid or the cancelled state - this can be configured on an account by account basis in …
> Added `unpaid` and `past_due` subscription status as paid member

- packages/magic-link/index.js
- packages/members-api/index.js
- Removed magic link email for upgrade checkout 
Previously, we were sending a magic link email to signup in case a logged-in member upgrades to a paid account, as we didn't check for logged in status while sending the magic link and always sent one on finishing checkout. Since Portal allows members to upgrade their account from free, it doesn't make sense to send another email to signup after completing checkout.
The fix here adds a metadata `checkoutType` to checkout session creation which can be passed in with `upgrade` value to denote an existing member is upgrading and doesn't need an email.
- Added request source option for magic link url 
Currently, Ghost uses standard query params like action, success and stripe for all actions and redirects to a site for member events. This …
> Added custom action for Portal and email fix

- packages/members-api/lib/stripe/index.js
no-issue
This ensures that we keep our local database in sync with the metadata in Stripe
> Stored cancellation reason in local database

- packages/members-api/lib/repositories/member/index.js
no-issue
If we receive webhooks out of order, e.g. a
`customer.subscription.updated` with a status of 'active', followed by a
`customer.subscription.created` with a status of 'incomplete'. We would
overwrite the correct value with data from the "older" webhook. This
ensures that we always fetch the latest data from the Stripe API before
storing in the database.
> Ensured latest subscription data is always stored

- packages/members-api/lib/services/stripe-webhook/index.js
no-issue
Fetching relations via the model returns a promise, and this was missing
the `await` keyword
> Fixed webhook handling for setup Checkout Sessions

- packages/members-api/lib/repositories/member/index.js
refs https://github.com/TryGhost/Team/issues/595
For a canceled subscription, the desired MRR delta is to reduce by negative of original amount, but our logic was incorrectly reducing it by double which led to big gap between real MRR and one shown on Dashboard.
- Fixes calculation for MRR change for canceled subscriptions
> 🐛 Fixed incorrect mrr delta calculation

- packages/members-api/lib/services/stripe-api/index.js
- packages/members-api/lib/services/stripe-plans/index.js
- packages/members-api/lib/services/stripe-webhook/index.js
- packages/members-api/package.json
- yarn.lock
refs https://github.com/TryGhost/Team/issues/593
- Bumps `stripe` library major version to v8 - 8.142
- Bumps default Stripe version to latest - '2020-08-27'
- Updated webhook Stripe version to latest - '2020-08-27'
- Removes `@types/stripe` in favor of first-class types support in `stripe` directly
- Updates types across files
> Updated Stripe major version and types

- packages/members-api/index.js
- packages/members-api/lib/migrations/index.js
- packages/members-api/lib/services/stripe-api/index.js
On Ghost Boot, as part of configuring Stripe, this populates stripe products and prices for existing stripe customers in the newly created `stripe_prices` and `stripe_products` table, which allows us to map existing customers to default Ghost product and on current prices. The population script on boot is only run if we find -
- No rows in `stripe_products`
- No rows in `stripe_prices`
- One or more rows in `members_stripe_customers_subscriptions`
> Populate stripe prices and products for existing customers

- packages/members-api/index.js
- packages/members-api/lib/repositories/member/index.js
- packages/members-api/lib/repositories/product/index.js
- packages/members-api/lib/services/stripe-api/index.js
refs https://github.com/TryGhost/Team/issues/619
On linking a stripe subscription to a member, this change -
- Adds missing stripe price or stripe product from subscription to DB
- Missing Stripe price is attached to the first Ghost Product if no matching Product exists
- Updates usage from plan to price in the `linkSubscription` method
- Updated products associated with a member based on active subscriptions
> Updated link subscription to handle missing stripe data

- packages/members-api/lib/repositories/member/index.js
- packages/members-api/lib/services/stripe-api/index.js
refs https://github.com/TryGhost/Members/commit/79513c58b578a404d41f446274dc04263c33fd7c
Following up on last commit, this moves up the expansion of Stripe customer fetch to always include `subscriptions` by default in api service so we don't accidentally miss it.
> Updated customer fetch from Stripe to include subscriptions

- packages/members-api/index.js
refs https://github.com/TryGhost/Team/issues/581
refs https://github.com/TryGhost/Team/issues/582
Content gating in Ghost is being expanded from basic public/members/free/paid to allowing full NQL queries. To facilitate quick matching of a member to the visibility query we need details of the associated labels and products alongside the basic member data.
> Added labels and products to fetched member identity data

- packages/members-api/index.js
- packages/members-api/lib/migrations/index.js
refs https://github.com/TryGhost/Team/issues/711
As this migration relies on the settings being populated, it cannot be a
standard migration in Ghost core, as the settings are populated by these
code migrations.
> Populated {monthly,yearly}_price_id from settings

- packages/members-api/index.js
- packages/members-api/lib/migrations/index.js
closes https://github.com/TryGhost/Team/issues/753
Currently, the portal_plans setting is storing price ids for active monthly/yearly prices for the default product, which was done to allow multiple prices in Portal. Since we only want to limit the prices for a Product to monthly/yearly, we are reverting the earlier migration and only store the available prices as monthly / yearly in portal setting instead of ids. Its also in sync with the approach in theme/API where we use named prices for monthly/yearly instead of price id list.
> Added migration to revert portal_plans setting to named values

- packages/members-csv/lib/parse.js
- packages/members-csv/lib/unparse.js
- packages/members-csv/test/unparse.test.js
refs https://github.com/TryGhost/Team/issues/765
Support for multiple products means we can no longer map a members state
to a csv row using just the `complimentary_plan` option. Instead we must
include the product(s) that a member has. This ensures that we can read
and write this data from/to csv files.
> Supported products column for `parse` & `unparse`

- packages/magic-link/package.json
- packages/members-api/lib/common.js
- packages/members-api/lib/controllers/member/index.js
- packages/members-api/lib/controllers/router/index.js
- packages/members-api/lib/services/stripe-api/index.js
- packages/members-api/package.json
- packages/members-ssr/index.js
- packages/members-ssr/package.json
- yarn.lock
no issue
- we're killing off `ghost-ignition` in favor of explicit packages
containing its individual components
- this commit switches the Members repo to using the
`@tryghost/ignition-errors` and `@tryghost/debug` dependencies,
updates the code with relevant changes and removes the `ghost-ignition`
dependency
> Removed used of `ghost-ignition` dependency

- packages/members-api/MembersAPI.js
- packages/members-api/lib/migrations.js
closes https://github.com/TryGhost/Team/issues/660
All subscriptions in Ghost are expected to have a corresponding price details in `stripe_price` table, which is used to determine the Stripe price a subscription is on. In some edge cases, specially before we started deleted old Stripe data during Stripe disconnect, it's possible that a subscription exists in DB without having a corresponding Stripe price in the DB. These subscriptions are not active for the connected Stripe account, and are save to remove. Going forward, all existing subscriptions with connected account will be removed when disconnecting stripe so we shouldn't have invalid subscriptions in DB in future.
The goal of this migration is to clean all such subscriptions from the DB to avoid any issues around missing price with …
> Added migration to remove invalid subscriptions

- packages/members-api/lib/migrations.js
closes https://github.com/TryGhost/Team/issues/778
- cleans up the stripe migration to add default monthly/yearly prices for sites, which had a possibility of using complimentary (0 amount prices) in edge cases
- adds missing return in the same migration for an unlikely failure to parse stripe plans
> Fixed stripe migration to avoid complimentary prices for monthly/yearly

- packages/members-ssr/lib/MembersSSR.js
refs https://github.com/TryGhost/Team/issues/908
The `cookies` module will unset a cookie if `null` or `undefined` is
passed as the value, or if the value is not passed. The previous call
was passing the options, which were being read as the value, and
resulting in `'[Object object]'` being stored as a cookie.
Explicitly passing `null` as the value makes this code correct and
easier to maintain.
> Fixed _removeSessionCookie method use of `cookies`

- packages/members-api/lib/repositories/product.js
refs https://github.com/TryGhost/Team/issues/919
As we pass the `benefits` to the Product model on creation, we do not
need to manually fetch them again. In fact doing so causes a strange SQL
error, where we attempt to run `SELECT undefined.*`.
> Removed superfluous benefits relation fetch

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/959
Because we were using the pre-existing products to determine a members
status, instead of the products _after_ we have handled the updates to
subscriptions, members with a paid subscription which was later canceled
were changed to 'comped' rather than 'free'. This adds a final check to
set a member to 'free' if their new set of products is empty.
> Fixed status when subscriptions are canceled

- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/services/member-bread.js
refs https://github.com/TryGhost/Team/issues/873
This ensures that all requests to the API will include the mock
subscriptions for comped members. Allowing the Admin to correctly shwo
the subscription information after adding and editing members. As well
as having the correct information when navigating from the list of
members to an individual member.
> Added browse, edit & add methods to MemberBREADService

- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/repositories/member.js
- packages/members-api/lib/services/token.js
refs https://github.com/TryGhost/Team/issues/1057
This method will validate a token, and then return the member associated
with it. Rather than exposing token validation and coupling consumers to
the structure of the token response data.
> Added ability to fetch member by identity token

- jsconfig.json
- packages/express-dynamic-redirects/.eslintrc.js
- packages/express-dynamic-redirects/LICENSE
- packages/express-dynamic-redirects/README.md
- packages/express-dynamic-redirects/index.js
- packages/express-dynamic-redirects/lib/DynamicRedirectManager.js
- packages/express-dynamic-redirects/package.json
- packages/express-dynamic-redirects/test/.eslintrc.js
- packages/express-dynamic-redirects/test/DynamicRedirectManager.test.js
- yarn.lock
refs https://github.com/TryGhost/Team/issues/1091
The Offers feature needs to be able to add and remove redirects to Ghost
- which is very similar to the custom routes functionality. Here we've
pulled out the core of the dynamic redirects so that it can be used by
both features and have code shared between them.
> Added express-dynamic-redirects module

- packages/members-api/lib/MembersAPI.js
refs https://github.com/TryGhost/Team/issues/1083
The Offers service is going to need access to the StripeAPIService too,
so we must pull its initialisation out of this module up to the Ghost
application layer, which will allow us to pass a reference of the
StripeAPIService to wherever needs it.
> Updated MembersAPI to take StripeAPIService as dep

- packages/members-api/lib/services/stripe-webhook.js
- packages/members-api/test/unit/lib/services/stripe-webhook.test.js
closes https://github.com/TryGhost/Team/issues/1238
- previously returned 500 errors when a subscription had multiple prices due to external tampering on Stripe directly
- instead now returns 400 Bad Request error in such scenario
> 🐛 Fixed 500 webhook errors for subscription with multiple prices

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/1275
We want to be able to track where member subscriptions came from, so
that we can use the information to reduce spam imports of members.
We were missing information when members were uploaded via the Admin
API, and setting the source to 'member' be default - this fixes that
both when creating members and when updating their subscription status.
> Added "api" source to MemberSubscribedEvents

- packages/members-api/lib/migrations.js
- packages/members-api/lib/repositories/member.js
- packages/members-api/lib/repositories/product.js
- packages/members-importer/lib/importer.js
refs https://github.com/TryGhost/Team/issues/1037
Tiers have a new `type` column as to differentiate between `free` and `paid` tiers. This change -
- sets type as paid for all new tiers created, as `free` tier is created by default
- ignores any `type` changes for add/edit of tiers, as `free` tier is always included by default and all other tiers can only be `paid`
- excludes any price/stripe data change for free tier
> Handled new type column for tiers

- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/controllers/router.js
- packages/stripe/lib/StripeAPI.js
- packages/stripe/lib/StripeService.js
- packages/stripe/package.json
- packages/stripe/test/unit/lib/StripeAPI.test.js
- yarn.lock
refs https://github.com/TryGhost/Team/issues/1322
We no longer restart the Members service based on the Stripe service
being updated, which meant that if it was initially configured with
missing URL's and later Stripe connected, it would not get the new
config until a server restart. This moves the last of Stripe config into
the Stripe service, so that all things concerning Stripe can be handled
in one place and updated together.
> Moved the last of the Stripe config out of Members

- packages/stripe/lib/StripeService.js
refs https://github.com/TryGhost/Toolbox/issues/214
- After disconnecting Stripe API the `_configured` flag stayed as `true`, causing behaviors as if Stripe was still connnected.
- The `api.configure` method was never reachable when disconnecting Stripe API, thus causes hanging "configured === false" state inside of the StripeAPI wrapper
> 🐛 Fixed StripeAPI disconnection

- packages/member-events/index.js
- packages/member-events/lib/MemberPageViewEvent.js
- packages/members-events-service/.eslintrc.js
- packages/members-events-service/LICENSE
- packages/members-events-service/README.md
- packages/members-events-service/index.js
- packages/members-events-service/lib/index.js
- packages/members-events-service/lib/last-seen-at-updater.js
- packages/members-events-service/package.json
- packages/members-events-service/test/.eslintrc.js
- packages/members-events-service/test/last-seen-at-updater.test.js
- packages/members-events-service/test/utils/assertions.js
- packages/members-events-service/test/utils/index.js
- packages/members-events-service/test/utils/overrides.js
- yarn.lock
refs https://github.com/TryGhost/Team/issues/1306
This introduces a new event: `MemberViewEvent`. And a listener that reacts to this event by updating the `member.last_seen_at` timestamp.
More details in the commits.
> Added an updater for the `last_seen_at` member field

- packages/members-api/lib/repositories/product.js
refs https://github.com/TryGhost/Team/issues/1387
First, this default value didn't make sense as it was written when we
had a boolean visible column, second, we don't need to add defaults here
- this implementation is super tied to the models anyway, so we may as
well rely on the model defaults - if we do pull it out similar to
Offers, then it may make sense to add a default there.
> Removed default for visibility

- packages/stripe/lib/Migrations.js
- packages/stripe/lib/StripeAPI.js
- packages/stripe/test/unit/lib/Migrations.test.js
no-issue
We had a bug where Tiers would have a name of 'Default Product', and a
Stripe Product would be created with the same name. This migration will
fixes those broken Stripe Products
> Added migration to update Stripe Product names

- packages/express-dynamic-redirects/lib/DynamicRedirectManager.js
- packages/express-dynamic-redirects/test/DynamicRedirectManager.test.js
refs https://ghost.slack.com/archives/C02G9E68C/p1647599592576139
When you add a redirect multiple times, and remove it afterwards, an error was thrown:
`Cannot destructure property 'fromRegex' of 'this.redirects[redirectId]' as it is undefined.`
> Fixed adding same redirect multiple times throws an error on removal 

- packages/members-api/lib/services/member-bread.js
no issue
- When: a new member is added via the API, with a stripe_customer_id.
- The member bread service's `add` method is called with a default option: `withRelated: ['labels']`.
- This option is passed along to the member repository (and consecutive calls) and is also passed when loading relations that don't have a relationship called 'labels'.
- This results in a `labels is not defined on the model` error when you try to create a new member with a stripe customer id.
- Test that found this issue will be added to the Ghost repo: https://github.com/TryGhost/Ghost/pull/14333
> Fixed 'labels is not defined on the model' error

- packages/stripe/lib/Migrations.js
- packages/stripe/lib/StripeAPI.js
- packages/stripe/lib/StripeService.js
- packages/stripe/test/unit/lib/Migrations.test.js
no issue
- When Ghost is running in a test mode by default it is configured with an invalid Stripe key that looks like `sk_test***`. In this case the migrations still try runnig creating requiest to Stripe that fail. The failures pollute the log, which makes other valid errors to be lost.
- An example of such error log is following:
```
Invalid API Key provided: sk_test_******ripe
----------------------------------------
Error: Invalid API Key provided: sk_test_******ripe
at res.toJSON.then.StripeAPIError.message (/home/naz/Workspace/Ghost/Ghost/node_modules/stripe/lib/StripeResource.js:214:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
- There doesn't seem to be a good reason to do migrations in the test mode, so skipping them as a special case to fix the …
> Fixed failing migration requests when client runs in a test mode

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/1248
blocked by https://github.com/TryGhost/Ghost/pull/14433
This fixes the issue with duplicate subscriptions being inserted because
concurrent calls to linkSubscription did not have rows locked.
> Used `FOR UPDATE` lock for linkSubscription reads

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/1454
Updates the MRR events to store the type column for existing events, this
includes expired events.
---
refs https://github.com/TryGhost/Team/issues/1302
Creates MRR events when the cancelled status of a subscription has changes
---
refs https://github.com/TryGhost/Team/issues/1453
Updates the cancelled MRR Event logic to make a negative MRR delta, this
is behind a flag so everything can be release at once
> Updated MRR events

- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/repositories/member.js
- packages/payments/lib/payments.js
refs https://github.com/TryGhost/Team/issues/1519
- Added offer repository dependency to member repository (offerAPI didn't work because it creates a new transaction that resulted in a deadlock during tests)
- Store the offer id from the Stripe subscription metadata in the subscription (only if the discount is still active)
- Also added the offer id to the metadata for a Stripe coupon, this will make adding and removing coupons a bit more foolproof
- Prefer the usage of the offer metadata from a coupon if it is present
- When no discount is applied to a subscription, it always sets the offer id to null, even when the metadata still contains the offer
- The offer_id remains stored when a subscription is canceled/expired
> Stored offer_id in subscriptions

- packages/members-api/lib/repositories/member.js
- packages/offers/lib/application/OfferRepository.js
- packages/payments/lib/payments.js
refs https://github.com/TryGhost/Team/issues/1519
- Removed offer metadata again from offer (added in one of the previous commits)
- Added `getByStripeCouponId` method in offer repository (required to find an offer based on the stripe_coupon_id)
- Match discounts from Stripe based on the stripe_coupon_id instead of metadata
> Updated offer_id matching logic to use stripe_coupon_id instead of metadata

- packages/members-api/lib/services/member-bread.js
refs https://github.com/TryGhost/Team/issues/1520
- Instead of doing the matching of the offers and subscriptions by looking at the offer redemptions, we can now look at the offer_id from subscriptions.
- This also fixes an issue where we don't attach the offer object to subscriptions in the members' browse method
- Updated browse behaviour to match the read behaviour of members (product relation needs to get loaded because it is missing in member.products if the subscription is expired).
Tests in https://github.com/TryGhost/Ghost/pull/14515
> Updated member bread service to return member subscription offers from offer_id column

- packages/members-api/lib/repositories/member.js
- packages/members-importer/lib/importer.js
- packages/members-importer/test/importer.test.js
no issue
When importing members, the members-importer isn't aware of the context and therefore falls back to use `member` as a source in members event table. This makes it impossible to determine imported members from others.
- Added an `context` property to the options in the members-importer constructor
- Checked for `importer` context when creating member events and assigned the source `admin` to it
> Allow setting context for members importer and use correct source

- packages/members-api/lib/repositories/member.js
- packages/members-events-service/lib/last-seen-at-updater.js
- packages/members-events-service/test/last-seen-at-updater.test.js
refs https://ghost.slack.com/archives/C02G9E68C/p1651488536238499
Changes needed in main repo:
1. **In `core/server/services/members/service.js`**
```
new LastSeenAtUpdater({
models: {
Member: models.Member
},
services: {
domainEvents: DomainEvents,
settingsCache
},
getMembersApi: () => module.exports.api
});
```
2. **Add newsletters undefined protection in `core/server/api/canary/utils/serializers/output/members.js`**
> Fixed member webhooks

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/1580
- When you tried to update a member that doesn't exist, an internal error was thrown
- It should throw a 'not found' error instead
- Optimized when to fetch the initialMember
Tests for 4.x in https://github.com/TryGhost/Ghost/pull/14657
Tests for 5.x in https://github.com/TryGhost/Ghost/pull/14658
> Fixed updating not existing member not throwing

- packages/members-api/lib/repositories/member.js
refs https://ghost.slack.com/archives/C02G9E68C/p1652980792270029
requires https://github.com/TryGhost/Ghost/pull/14870
When bulk unsubscribing members, the number of deleted newsletter relations are returned instead of the number of members with newsletters that were cleared. This update deletes newsletter relations on member_id, so we can return the count of members instead of newsletter relations that were deleted.
> Improved bulk unsubscribe operation to use member_id column

- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/controllers/router.js
refs https://github.com/TryGhost/Team/issues/1526
We weren't using the `req.body.customerEmail` to load a member and
check their existing tiers, this meant that existing members which
were signed out and attempted to create a stripe checkout session were
able to.
> Fixed checkout session creation for existing members

- packages/members-api/lib/repositories/member.js
- packages/members-api/lib/services/member-bread.js
refs https://github.com/TryGhost/Team/issues/1674
- The `comped` flag was present in v3 Members API and was unintentionally dropped in v4/v5 APIs without noticing. The support is necessary to keep integrations like Zapier working. The flag should be phased out following the version header pattern that has been introduced in Ghost v5.
Egg, is this well placed or maybe could be showed in a different stage of "editing" the member? There's so many things going on in the create/update methods I decided to shove the change mostly by the end of methods to not disrupt anything accidentally.
> Fixed support for `comped` flag in members

- packages/magic-link/lib/MagicLink.js
- packages/magic-link/test/index.test.js
- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/controllers/router.js
refs https://github.com/TryGhost/Team/issues/1174
This paves the way for Ghost to be able to redirect to the referrer
page when dealign with signup magic links. We pass the referrer for
all types of magic links however, to allow extension of this
functionality in the future.
We've also removed the concept of `requestSrc` which has been unused
for a while now.
> Passed request referrer to magic link service
