TryGhost/Members

- packages/members-ssr/.eslintrc.js
- packages/members-ssr/LICENSE
- packages/members-ssr/README.md
- packages/members-ssr/example.js
- packages/members-ssr/index.js
- packages/members-ssr/package.json
- packages/members-ssr/test/.eslintrc.js
- packages/members-ssr/test/hello.test.js
- packages/members-ssr/test/utils/assertions.js
- packages/members-ssr/test/utils/index.js
- packages/members-ssr/test/utils/overrides.js
- packages/sdk/theme-dropin/src/index.js
- yarn.lock
This module provides two helpers for implementing server side rendering with members.
> Members SSR

- packages/members-theme-bindings/.eslintrc.js
- packages/members-theme-bindings/LICENSE
- packages/members-theme-bindings/README.md
- packages/members-theme-bindings/index.js
- packages/members-theme-bindings/package.json
- packages/members-theme-bindings/test/.eslintrc.js
- packages/members-theme-bindings/test/hello.test.js
- packages/members-theme-bindings/test/utils/assertions.js
- packages/members-theme-bindings/test/utils/index.js
- packages/members-theme-bindings/test/utils/overrides.js
- yarn.lock
> Added members-theme-bindings module

- packages/members-theme-bindings/index.js
no-issue
This gives greater flexibility in the application which handles the urls
for this, allowing the urls to be changed and configured in only one
codebase.
> Removed hardcoded url values

- packages/members-api/index.js
- packages/members-api/lib/tokens.js
- packages/members-api/lib/users.js
- packages/members-api/package.json
- packages/members-ssr/index.js
This updates the core member-api package to use the magic link functionality.
Also updates the members-ssr package to work with the magic link flow.
Removes all payment support - this will be added back in the future
> Updates for magic link

- packages/members-api/index.js
> Logged error when sending email

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
This allows the stripe checkout flow to be entered without an existing member identity. So that we can start creating members after a payment is received.
> Support payment first in members-api

- packages/members-api/index.js
- packages/members-api/lib/users.js
no-issue
This allows us to give more functionality to consumers, with a smaller
API (rather than exposing the methods for sending a magic-link email)
> Added flag to create member for sending email

- packages/members-api/lib/users.js
> Fixed signature for listMembers call

- packages/magic-link/package.json
- packages/members-api/package.json
- packages/members-ssr/package.json
- @tryghost/magic-link@0.1.4
- @tryghost/members-api@0.6.2
- @tryghost/members-ssr@0.5.2
> Published new versions

- packages/members-api/index.js
- packages/members-api/lib/stripe/api/createStripeRequest.js
- packages/members-api/lib/stripe/api/stripeRequests.js
- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
> Fixed webhook creating and improved logging/debug

- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
> Ensured customers are deleted when members are

- packages/members-api/index.js
- packages/members-api/lib/stripe/api/stripeRequests.js
- packages/members-api/lib/stripe/index.js
- packages/members-ssr/index.js
This updates the stripe info attached to members
now you will have a member like:
```
{
stripe: {
subscriptions:[{
customer: 'customer_id',
subscription: 'subscription_id',
plan: 'plan_id',
status: 'subscription status',
name: 'plan nickname e.g. "Monthly"'
interval: 'how often plan charges e.g "month", "year"',
amount: 'amount in smallest denomination e.g. cents',
currency: 'e.g. usd',
last4: 'last four digits of card OR null',
validUntil: 'epoch timestamp of when current interval ends IN SECONDS'
}]
}
}
```
> Stripe data updates

- packages/members-api/index.js
> Added some small features

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
- packages/members-ssr/index.js
> Cache stripe data locally

- packages/magic-link/index.js
- packages/magic-link/test/index.test.js
- packages/members-api/index.js
no-issue
This makes magic-link tokens much shorter, so they are not as obnoxious in emails
> Made magic-link tokens shorter

- packages/members-api/lib/users.js
> Included subscription information when listing members

- packages/members-api/index.js
- packages/members-api/lib/users.js
This PR is just an FYI for @allouis :slightly_smiling_face: and reference point for core.
> Refactored user CRUD to be usable by Ghost core

- .travis.yml
- renovate.json
no issue
- we want to test using all LTS versions
> Updated to test using all Node LTS versions

- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
refs https://github.com/TryGhost/Ghost/pull/11539
PR here only for for reference reason.
> ✨ Added ability to link member to existing stripe customer

- packages/substack-ghost-csv-converter/.eslintrc.js
- packages/substack-ghost-csv-converter/LICENSE
- packages/substack-ghost-csv-converter/README.md
- packages/substack-ghost-csv-converter/bin/index.js
- packages/substack-ghost-csv-converter/index.js
- packages/substack-ghost-csv-converter/lib/converter.js
- packages/substack-ghost-csv-converter/lib/format-csv.js
- packages/substack-ghost-csv-converter/lib/index.js
- packages/substack-ghost-csv-converter/lib/normalize-members-csv.js
- packages/substack-ghost-csv-converter/package.json
- packages/substack-ghost-csv-converter/test/.eslintrc.js
- packages/substack-ghost-csv-converter/test/fixtures/substack-csv-format.csv
- packages/substack-ghost-csv-converter/test/hello.test.js
- packages/substack-ghost-csv-converter/test/lib/normalize-members-csv.test.js
- packages/substack-ghost-csv-converter/test/utils/assertions.js
- packages/substack-ghost-csv-converter/test/utils/index.js
- packages/substack-ghost-csv-converter/test/utils/overrides.js
- yarn.lock
The module is a result of extraction of temporary code that was placed in core - https://github.com/TryGhost/Ghost/pull/11539/commits/737173ac39d352fd51af05230c58b18f3d1a5a80. Allows automating Substack to Ghost Member migration
> ✨ Added Substack to Ghost CSV converter package

- packages/magic-link/index.js
- packages/members-api/index.js
> Exposed getMagicLink method

- packages/members-api/lib/stripe/index.js
Added plan nickname fallback to empty string (description in commit message)
> Added plan nickname fallback to empty string

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
ronseal
Refs: https://stripe.com/docs/payments/checkout/subscriptions/updating#set
> Added middleware to handle billing updates 

- package.json
- packages/members-api/index.js
- packages/members-api/lib/geolocation.js
- packages/members-api/lib/users.js
- packages/members-api/package.json
- packages/members-api/test/.eslintrc.js
- packages/members-api/test/unit/lib/geolocation.test.js
- yarn.lock
requires https://github.com/TryGhost/Ghost/commit/f38d490886233ecb355faccd0cab1acbe7aea2b4
- adds `lib/geolocation.js` with `getGeolocationFromIP()` function which uses https://geojs.io to lookup geolocation data from an IPv4 or IPv6 address
- updates `create/updateMember()` functions to work with a `geolocation` property in the passed in object
- if `geolocation` is `undefined` when updating a member do not reset any existing property
- updates `sendMagicLink` middleware to extract the IP address from the request and stores it as part of the token payload
- updates `getMemberDataFromMagicLinkToken()` method to extract the IP address from the token payload and perform a geolocation lookup if we have an IP address and a matching member does not already have geolocation data
> ✨ Store geolocation data during member signup/signin

- packages/members-api/lib/stripe/index.js
> Used plans trial by default for checkout sessions

- packages/members-api/index.js
refs https://github.com/TryGhost/members.js/issues/30
- Updates `sendMagicLink` middleware to allow adding old email address to payload. Checks for if new email address already exists in db before creating magic link, throws error in case of duplicate email.
- Updates magic link parsing for data to check if the intention is to update email address and update member's email to new email address in case its allowed.
- Return session data from magic link using the new email address
> Updated magic link flow to allow changing member's email

- packages/members-api/index.js
- packages/members-ssr/index.js
closes https://github.com/TryGhost/Members/issues/148
- geolocation was not being fetched/stored for paid member signup
- magic link was being sent after Stripe webhook but we don't have an IP at that stage
- it only worked when a magic link was requested by the browser
- moved the geolocation fetch/update to `members-ssr`
- kept the ip geolookup and storage inside `members-api` but exposed it as a method so consumers are able to choose when it's performed
- used the new api method in `members-ssr` when exchanging a token from the session as that is always driven by browser requests so we know we have an IP and it's likely the correct one (reliant on consumers having "trust proxy" config correct)
- stopped storing IP addresses in the token payload (keeps links shorter)
> Moved members geolocation fetch/update into members-ssr

- packages/members-api/index.js
no-issue
This can be used by Ghost to determine if the Stripe keys can be deleted
> Added hasActiveStripeSubscriptions method

- packages/members-api/lib/users.js
refs https://github.com/TryGhost/Ghost/issues/12127
- Adds new `updateSubscription` method to members-api which allows updating individual subscription for a member
- Currently method only allows toggling of cancellation at period end for a subscription directly
> Added update subscription method to members api

- packages/members-api/index.js
- packages/members-api/lib/stripe/index.js
This adds the initial support for cancellation_reason param and will set it on the subscription metadata.
> [WIP] Added support for cancellation_reason

- packages/members-api/index.js
- packages/members-api/lib/metadata.js
- packages/members-api/lib/stripe/index.js
- packages/members-api/lib/users.js
- packages/members-csv/lib/parse.js
- packages/members-csv/lib/unparse.js
- packages/members-csv/test/parse.test.js
no-issue
- updates members-api to error rather than fail silently
- updates members-api to allow passing options
- updates members-csv to handle value mapping when parsing
- updates members-csv to handle error column when unparsing
> Importer improvements

- packages/members-api/index.js
- packages/members-api/lib/controllers/router/index.js
no-issue
This fixes a bug when a checkout session is created without passing
custom redirect URL's.
> Passed default URL's when creating checkout session

- packages/members-api/lib/repositories/member/index.js
refs https://github.com/TryGhost/Ghost/pull/12570
> Updated Member Repository to ensure status flag is synced

- packages/members-api/index.js
- packages/members-api/lib/services/stripe-api/index.js
- packages/members-api/lib/services/stripe-plans/index.js
- packages/members-api/lib/services/stripe-webhook/index.js
refs https://github.com/TryGhost/Ghost/issues/12448
> Threw "fatal" errors for non-prod usage of live Stripe data

- packages/members-api/lib/repositories/product/index.js
refs https://github.com/TryGhost/Team/issues/616
- Allows editing name(nickname) of an existing price via the API
> Updated product repo to allow editing price names

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/542
Importing members with a created_at date will incorrectly create events
for the member for the date of the import. This updates our event
handling to use either the passed created_at date, or in the case of
subscriptions the start_date of the subscription. We're using start_date
for subscriptions rather than created, as this is more accurate because
start_date works correctly for backdated subscriptions in Stripe.
> Fixed created_at dates for member event objects

- .github/CODEOWNERS
> Added @daniellockyer as codeowner for migrations.js

- packages/members-api/lib/MembersAPI.js
- packages/members-api/lib/controllers/well-known.js
refs https://github.com/TryGhost/Team/issues/664
The well known controller is designed to handle any requests to the
/.well-known endpoint where the members app is mounted. The first and
only requirement so far is that we expose a JSON Web Key Set so that
external services are able to validate Members JWT's
> Added WellKnownController and exposed jwks.json

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/1456
Simplifies the calculation of MRR deltas, which will make it easier to update MRR to include offers and cancellations in the future.
> Updated member mrr_delta calculation to use stored mrr

- packages/offers/lib/application/OfferRepository.js
refs https://github.com/TryGhost/Ghost/pull/14488
**Bug:**
When creating a new offer, sometimes no discount object is created in Stripe (only in MySQL). This issue causes tests to fail in https://github.com/TryGhost/Ghost/pull/14488
**Cause:**
When creating an offer with the OffersAPI, we create a new transaction to save the offer and check for uniqueness. Inside that transaction, we dispatch an OfferCreatedEvent event before the transaction is committed to the database.
When listening for this event in the `members-payments` package, we create the discount object in Stripe and save the stripe_coupon_id to the newly created offer. But because (in most cases) the offer doesn't yet exist in the database, that listener fails without warning and exits early.
**Solution:**
Creating a discount …
> Fixed OfferCreatedEvent being dispatched before the transaction has been committed

- packages/members-api/lib/MembersAPI.js
refs https://github.com/TryGhost/Team/issues/1147
This endpoint is no longer used in 5.0
> Removed hasActiveStripeSubscriptions method

- packages/members-api/lib/repositories/member.js
refs https://github.com/TryGhost/Team/issues/1606
> Fixed issue with filter transform not applying to bulk operations
